//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Change.Contracts.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class COSContracts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal COSContracts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Change.Contracts.Resources.COSContracts", typeof(COSContracts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto prolongation.
        /// </summary>
        internal static string ChangeColContractAutoProlongation {
            get {
                return ResourceManager.GetString("ChangeColContractAutoProlongation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto prolongation period.
        /// </summary>
        internal static string ChangeColContractAutoProlonPeriod {
            get {
                return ResourceManager.GetString("ChangeColContractAutoProlonPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collateral description.
        /// </summary>
        internal static string ChangeColContractCollateralDesc {
            get {
                return ResourceManager.GetString("ChangeColContractCollateralDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collateral value.
        /// </summary>
        internal static string ChangeColContractCollateralValue {
            get {
                return ResourceManager.GetString("ChangeColContractCollateralValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract No..
        /// </summary>
        internal static string ChangeColContractContractNo {
            get {
                return ResourceManager.GetString("ChangeColContractContractNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract currency.
        /// </summary>
        internal static string ChangeColContractCurrency {
            get {
                return ResourceManager.GetString("ChangeColContractCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string ChangeColContractCustomerAddress {
            get {
                return ResourceManager.GetString("ChangeColContractCustomerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earliest cancelation date.
        /// </summary>
        internal static string ChangeColContractEarliestCancelationDate {
            get {
                return ResourceManager.GetString("ChangeColContractEarliestCancelationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        internal static string ChangeColContractEndDate {
            get {
                return ResourceManager.GetString("ChangeColContractEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General / Appendix.
        /// </summary>
        internal static string ChangeColContractGeneralAppendix {
            get {
                return ResourceManager.GetString("ChangeColContractGeneralAppendix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment schedule.
        /// </summary>
        internal static string ChangeColContractPaymentSchedule {
            get {
                return ResourceManager.GetString("ChangeColContractPaymentSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penalty.
        /// </summary>
        internal static string ChangeColContractPenalty {
            get {
                return ResourceManager.GetString("ChangeColContractPenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency of penalty.
        /// </summary>
        internal static string ChangeColContractPenaltyCurrency {
            get {
                return ResourceManager.GetString("ChangeColContractPenaltyCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract sign date.
        /// </summary>
        internal static string ChangeColContractSignDate {
            get {
                return ResourceManager.GetString("ChangeColContractSignDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string ChangeColContractStartDate {
            get {
                return ResourceManager.GetString("ChangeColContractStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string ChangeColContractStatus {
            get {
                return ResourceManager.GetString("ChangeColContractStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract substance.
        /// </summary>
        internal static string ChangeColContractSubstance {
            get {
                return ResourceManager.GetString("ChangeColContractSubstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtype.
        /// </summary>
        internal static string ChangeColContractSubtype {
            get {
                return ResourceManager.GetString("ChangeColContractSubtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtype2.
        /// </summary>
        internal static string ChangeColContractSubtype2 {
            get {
                return ResourceManager.GetString("ChangeColContractSubtype2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ChangeColContractSubTypeDesc {
            get {
                return ResourceManager.GetString("ChangeColContractSubTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termination notice period.
        /// </summary>
        internal static string ChangeColContractTerminationNP {
            get {
                return ResourceManager.GetString("ChangeColContractTerminationNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract total value.
        /// </summary>
        internal static string ChangeColContractTotalValue {
            get {
                return ResourceManager.GetString("ChangeColContractTotalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ChangeColContractType {
            get {
                return ResourceManager.GetString("ChangeColContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of penalty.
        /// </summary>
        internal static string ChangeColContractValueOfPenalty {
            get {
                return ResourceManager.GetString("ChangeColContractValueOfPenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string ChangeColContractVendorAddress {
            get {
                return ResourceManager.GetString("ChangeColContractVendorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning date.
        /// </summary>
        internal static string ChangeColContractWarnDate {
            get {
                return ResourceManager.GetString("ChangeColContractWarnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract yearly value.
        /// </summary>
        internal static string ChangeColContractYearlyValue {
            get {
                return ResourceManager.GetString("ChangeColContractYearlyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other info.
        /// </summary>
        internal static string ChangeColContracVendorOtherInfo {
            get {
                return ResourceManager.GetString("ChangeColContracVendorOtherInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer contact person.
        /// </summary>
        internal static string ChangeColCustContactPerson {
            get {
                return ResourceManager.GetString("ChangeColCustContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string ChangeColCustomer {
            get {
                return ResourceManager.GetString("ChangeColCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer profit center.
        /// </summary>
        internal static string ChangeColCustPCenter {
            get {
                return ResourceManager.GetString("ChangeColCustPCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer external contact.
        /// </summary>
        internal static string ChangeColExtCustContact {
            get {
                return ResourceManager.GetString("ChangeColExtCustContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor external contact.
        /// </summary>
        internal static string ChangeColExtVendorContact {
            get {
                return ResourceManager.GetString("ChangeColExtVendorContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group entity.
        /// </summary>
        internal static string ChangeColGroupEntity {
            get {
                return ResourceManager.GetString("ChangeColGroupEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        internal static string ChangeColVendor {
            get {
                return ResourceManager.GetString("ChangeColVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor contact person.
        /// </summary>
        internal static string ChangeColVendorContactPerson {
            get {
                return ResourceManager.GetString("ChangeColVendorContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangeContractOverdueBody.
        /// </summary>
        internal static string ChangeContractOverdueBody {
            get {
                return ResourceManager.GetString("ChangeContractOverdueBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangeContractOverdueTitle.
        /// </summary>
        internal static string ChangeContractOverdueTitle {
            get {
                return ResourceManager.GetString("ChangeContractOverdueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE Contract subtype.
        /// </summary>
        internal static string CHANGEContractSubType {
            get {
                return ResourceManager.GetString("CHANGEContractSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create contract subtype.
        /// </summary>
        internal static string CHANGEContractSubTypeDescr {
            get {
                return ResourceManager.GetString("CHANGEContractSubTypeDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE Contract.
        /// </summary>
        internal static string ChangeCTContract {
            get {
                return ResourceManager.GetString("ChangeCTContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create contract.
        /// </summary>
        internal static string ChangeCTContractDescr {
            get {
                return ResourceManager.GetString("ChangeCTContractDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE Contract document.
        /// </summary>
        internal static string ChangeCTContractDocu {
            get {
                return ResourceManager.GetString("ChangeCTContractDocu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create contract document.
        /// </summary>
        internal static string ChangeCTContractDocuDescr {
            get {
                return ResourceManager.GetString("ChangeCTContractDocuDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE Customer.
        /// </summary>
        internal static string ChangeCTCustomer {
            get {
                return ResourceManager.GetString("ChangeCTCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create customer.
        /// </summary>
        internal static string ChangeCTCustomerDescr {
            get {
                return ResourceManager.GetString("ChangeCTCustomerDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE Profit center.
        /// </summary>
        internal static string ChangeCTCustomerPC {
            get {
                return ResourceManager.GetString("ChangeCTCustomerPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create customer profit center.
        /// </summary>
        internal static string ChangeCTCustomerPCDescr {
            get {
                return ResourceManager.GetString("ChangeCTCustomerPCDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE External contact.
        /// </summary>
        internal static string ChangeCTExternalContact {
            get {
                return ResourceManager.GetString("ChangeCTExternalContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create external contact.
        /// </summary>
        internal static string ChangeCTExternalContactDescr {
            get {
                return ResourceManager.GetString("ChangeCTExternalContactDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE Group entity.
        /// </summary>
        internal static string ChangeCTGroupEntity {
            get {
                return ResourceManager.GetString("ChangeCTGroupEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create group entity.
        /// </summary>
        internal static string ChangeCTGroupEntityDescr {
            get {
                return ResourceManager.GetString("ChangeCTGroupEntityDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE Vendor.
        /// </summary>
        internal static string ChangeCTVendor {
            get {
                return ResourceManager.GetString("ChangeCTVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create vendor.
        /// </summary>
        internal static string ChangeCTVendorDescr {
            get {
                return ResourceManager.GetString("ChangeCTVendorDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts.
        /// </summary>
        internal static string ChangeListTitleContracts {
            get {
                return ResourceManager.GetString("ChangeListTitleContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract subtype.
        /// </summary>
        internal static string ChangeListTitleContractSubtype {
            get {
                return ResourceManager.GetString("ChangeListTitleContractSubtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer profit center.
        /// </summary>
        internal static string ChangeListTitleCustomerPC {
            get {
                return ResourceManager.GetString("ChangeListTitleCustomerPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string ChangeListTitleCustomers {
            get {
                return ResourceManager.GetString("ChangeListTitleCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External contacts.
        /// </summary>
        internal static string ChangeListTitleExternalContacts {
            get {
                return ResourceManager.GetString("ChangeListTitleExternalContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group entities.
        /// </summary>
        internal static string ChangeListTitleGroupEntity {
            get {
                return ResourceManager.GetString("ChangeListTitleGroupEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendors.
        /// </summary>
        internal static string ChangeListTitleVendors {
            get {
                return ResourceManager.GetString("ChangeListTitleVendors", resourceCulture);
            }
        }
    }
}
