//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Change.Contracts.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class COSContracts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal COSContracts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Change.Contracts.Resources.COSContracts", typeof(COSContracts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtype.
        /// </summary>
        internal static string ChangeColContractSubtype {
            get {
                return ResourceManager.GetString("ChangeColContractSubtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string ChangeColCustomer {
            get {
                return ResourceManager.GetString("ChangeColCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer profit center.
        /// </summary>
        internal static string ChangeColCustPCenter {
            get {
                return ResourceManager.GetString("ChangeColCustPCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer external contact.
        /// </summary>
        internal static string ChangeColExtCustContact {
            get {
                return ResourceManager.GetString("ChangeColExtCustContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor external contact.
        /// </summary>
        internal static string ChangeColExtVendorContact {
            get {
                return ResourceManager.GetString("ChangeColExtVendorContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group entity.
        /// </summary>
        internal static string ChangeColGroupEntity {
            get {
                return ResourceManager.GetString("ChangeColGroupEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        internal static string ChangeColVendor {
            get {
                return ResourceManager.GetString("ChangeColVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE Contract subtype.
        /// </summary>
        internal static string CHANGEContractSubType {
            get {
                return ResourceManager.GetString("CHANGEContractSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create contract subtype.
        /// </summary>
        internal static string CHANGEContractSubTypeDescr {
            get {
                return ResourceManager.GetString("CHANGEContractSubTypeDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE Contract.
        /// </summary>
        internal static string ChangeCTContract {
            get {
                return ResourceManager.GetString("ChangeCTContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create contract.
        /// </summary>
        internal static string ChangeCTContractDescr {
            get {
                return ResourceManager.GetString("ChangeCTContractDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE Customer.
        /// </summary>
        internal static string ChangeCTCustomer {
            get {
                return ResourceManager.GetString("ChangeCTCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create customer.
        /// </summary>
        internal static string ChangeCTCustomerDescr {
            get {
                return ResourceManager.GetString("ChangeCTCustomerDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE Profit center.
        /// </summary>
        internal static string ChangeCTCustomerPC {
            get {
                return ResourceManager.GetString("ChangeCTCustomerPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create customer profit center.
        /// </summary>
        internal static string ChangeCTCustomerPCDescr {
            get {
                return ResourceManager.GetString("ChangeCTCustomerPCDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE External contact.
        /// </summary>
        internal static string ChangeCTExternalContact {
            get {
                return ResourceManager.GetString("ChangeCTExternalContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create external contact.
        /// </summary>
        internal static string ChangeCTExternalContactDescr {
            get {
                return ResourceManager.GetString("ChangeCTExternalContactDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE Group entity.
        /// </summary>
        internal static string ChangeCTGroupEntity {
            get {
                return ResourceManager.GetString("ChangeCTGroupEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create group entity.
        /// </summary>
        internal static string ChangeCTGroupEntityDescr {
            get {
                return ResourceManager.GetString("ChangeCTGroupEntityDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE Vendor.
        /// </summary>
        internal static string ChangeCTVendor {
            get {
                return ResourceManager.GetString("ChangeCTVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create vendor.
        /// </summary>
        internal static string ChangeCTVendorDescr {
            get {
                return ResourceManager.GetString("ChangeCTVendorDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts.
        /// </summary>
        internal static string ChangeListTitleContracts {
            get {
                return ResourceManager.GetString("ChangeListTitleContracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract subtype.
        /// </summary>
        internal static string ChangeListTitleContractSubtype {
            get {
                return ResourceManager.GetString("ChangeListTitleContractSubtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer profit center.
        /// </summary>
        internal static string ChangeListTitleCustomerPC {
            get {
                return ResourceManager.GetString("ChangeListTitleCustomerPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string ChangeListTitleCustomers {
            get {
                return ResourceManager.GetString("ChangeListTitleCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External contacts.
        /// </summary>
        internal static string ChangeListTitleExternalContacts {
            get {
                return ResourceManager.GetString("ChangeListTitleExternalContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group entities.
        /// </summary>
        internal static string ChangeListTitleGroupEntity {
            get {
                return ResourceManager.GetString("ChangeListTitleGroupEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendors.
        /// </summary>
        internal static string ChangeListTitleVendors {
            get {
                return ResourceManager.GetString("ChangeListTitleVendors", resourceCulture);
            }
        }
    }
}
